### ISSUE TITLE
Preparación de sentencias

### ISSUE THREAD

**Issue by aranzabe** [aranzabe/DWEBS_22_23#3]

**Comment by Alextorres20** [comment]
Hola

**Comment by jornu99** [comment]
NO

**Comment by jornu99** [comment]
Okay

**Comment by InesRM** [comment]
Porqué se incluye la conexión ( ejemplo de khatary) en la query?... una consulta normal a la base también vale?

**Comment by InesRM** [comment]
Select dni from personas where dni= 'dni'; a esto me refiero

**Comment by InesRM** [comment]
bueno en este caso dni= ?

**Comment by Alextorres20** [comment]
Si profe, ya me ha quedado tooo claro
